projectName: xxx-staging
#
# 
resources:
  requests:
    cpu: 100m
    memory: 250Mi
  limits:
    cpu: 200m
    memory: 500Mi
#
# 
hoge:
  - インデントが狂うかもしれない配列
  - インデントが狂うかもしれない配列
  - インデントが狂うかもしれない配列
# 消えるかもしれないコメント
versions:
  stable:
    image: gcr.io/my-images/hoge@sha256:c7569aa918ceb4c0b645dd829094c6cae0dd3e0bfff5ebb86eaf2dbd576b9d52
